Importujemy najpierw potrzebne pakiety

In [85]:
# zmiana frekwencji zapisu dzwieku - dodac do defs i funkcji glownej
# zmiana glosnosci calego dzwieku -to samo + stworzyc funkcje
# zmiana wag dla utworu - to samo

#http://www.cs.uregina.ca/Links/class-info/325/PythonSound/
#http://www.cs.usfca.edu/~brooks/S08classes/cs107/sound.html
#http://www.openbookproject.net/py4fun/wave/wave.html
#http://www.informit.com/articles/article.aspx?p=2355856&seqNum=5

import numpy as np
import scipy.io.wavfile
import scipy.signal

def wczytywanie_piosenki(nazwa_piosenki = "song.txt"):

    """
    wczytuje zawartosc pliku song.txt do macierzy numpy-owej
    
    arg:
        str: nazwa_piosenki - nazwa pliku tekstowego wraz z rozszerzeniem (zakladam, tak jak w opisie 
                              projektu, ze bedziemy korzystac z domyslnej wartosci, tj. "song.txt", wiec
                              nie sprawdzam poprawnosci typu tego argumentu; problemem z brakiem tego pliku
                              etc. zajmie sie juz python, wyrzucajac komunikat, wiec tez pomijam)
    
    wyjscie:
        numpy.ndarray (str: U2): song - macierz wymiaru 1 na k (ilosc wierszy w pliku song.txt), zawierajaca
                                        kolejne wiersze z wejsciowego pliku zapisane jako stringi
                                    
        
    """
    
    import numpy as np

    song = np.genfromtxt(nazwa_piosenki,dtype='str')
    
    return song

a = wczytywanie_piosenki()

In [90]:
def wczytywanie_sciezek(lista_trackow):
    """
    
    wczytuje na podstawie pliku "song.txt" (lub innego, ktory definiował lista_tackow) zawartosc plikow 
    "trackXY.txt" do jednej macierzy numpy-owej 
    
    arg:
        numpy.ndarray (str: U2): lista_trackow - macierz wymiaru 1 na k, zawierajaca zapisane jako napisy,
                                                 numery kolejnych sciezek do odtworzenia
    
    wyjscie:
        tuple: numpy.ndarray (str: U2): piosenka - macierz, zawierajaca jako wiersze kolejne cwiercnuty utworu,
                                            w kazdym wierszu informacja czy dany sample ma zagrac czy nie,
                                            zapisana jako napis (albo numer sampla albo --)
               bool: dobre_trackusie - zmienna kontrolujaca poprawnosc wczytywanych trackow (metrum i ilosc
                                       sampli)
                                            
    """
    
    import numpy as np
    
    # zapisujemy unikalne numery trackow, ktore maja byc wczytane
    jakie_sciezki = np.unique(lista_trackow)

    # slownik, ktorego kolejne elementy to unikalne sciezki (key) wraz z ich zawartoscia (value)
    sciezki = {}
    
    # zmienna do sprawdzenia czy zachowane jest odpowiednie metrum (liczba wierszy podzielna przez 4) w kazdej
    # ze sciezek, jesli nie, to zwracana macierz bedzie zerowa
    czy_4_na_4 = True
    
    # zmienna do sprawdzenia czy w kazdym tracku uzyto tyle samo sampli, jesli nie, zwracana macierz bedzie
    # zerowa
    czy_tyle_samo_sampli = True
    
    # lista zawierajaca ilosc uzytych sampli w kolejnych trackach
    ile_sampli = []
    
    # cale to definiowanie slownika i szukanie unikalnych trackow po to by raz wczytac zawartosc uzywanych
    # trackow a potem sie do niej odwolywac, a nie wczytywac za kazdym razem od nowa zawartosc trackow
    
    for ktora_sciezka in jakie_sciezki: # w iteratorze bierzemy napisy "01" "02" itd. stringi!!!
        
        # tworzymy napis z nazwa pliku tracka, np. "track01.txt"
        plik = ''.join(['track',ktora_sciezka,'.txt'])
        # wczytujemy zawartosc danego tracka do odpowiednio nazwanego elementu w slowniku sciezki
        sciezki[ktora_sciezka] = np.genfromtxt(plik, dtype='str')
        # dodajemy ilosc kanalow danego tracka do listy
        ile_sampli.append(sciezki[ktora_sciezka].shape[1])
        # sprawdzamy podzielnosc wierdzy danego tracka przez 4, jesli nie zachodzi, drukujemy odpowiedni
        # komunikat i zmieniamy wartosc zmiennej logicznej czy_4_na_4 na False
        if(sciezki[ktora_sciezka].shape[0] % 4 != 0):
            print("Plik: ", plik, " nie ma podzielnej przez 4 liczby wierszy")
            czy_4_na_4 = False

    
    # sprawdzamy czy ilosc uzytych sampli jest taka sama w kazdym tracku
    if(len(set(ile_sampli))!=1): # set-em wyciagamy unikalne wartosci i sprawdzamy czy jest tylko jedna taka
        print("Rozna liczba uzytych sampli w trackach")
        czy_tyle_samo_sampli = False
    
    # jedna zmienna odpowiadajaca za poprawnosc trackow
    dobre_trackusie = czy_4_na_4 and czy_tyle_samo_sampli
    
    # jesli metrum i ilosc sampli sie zgadza zapisujemy zawartosc sciezek w piosence do numpy.ndarraya
    if(dobre_trackusie):
 
            # do zapisu poslugujemy sie lista i funkcja append na liscie, gdyz jest to bardziej efektywne
            # niz append dla numpy.ndarraya, gdy nie znamy jego ostatecznych rozmiarow
            piosenka = []
            
             # tym razem iterujemy po kolejnych trackach z lista_trackow, nie po unikalnnych nazwach trackow
            for ktora_sciezka in lista_trackow:
                piosenka.append(sciezki[ktora_sciezka]) #dodajemy odpowiednia wartosc ze slownika sciezki

            #tworzymy z listy obiekt typu numpy.ndarray
            piosenka = np.array(piosenka)
            # obiekt ten zawiera kilka podmacierzy, wiec tworzymy z niego 1 macierz
            piosenka = np.vstack(piosenka)
    # gdy nie ma odpowiedniego metrum lub ilosci sampli zwracamy zerowa macierz      
    else: 
        piosenka = np.array([0])

    return piosenka, dobre_trackusie 

pios, k = wczytywanie_sciezek(a)

In [87]:
def wczytywanie_ustawien(plik_konfiguracyjny = "defs.txt"):
    """ 
    wczytywanie pliku z ustawieniami (pliku defs.txt) do slownika, na razie zakladam, ze parametry beda 
    liczbami
    
    arg:
        str: plik_konfiguracyjny - nazwa pliku konfiguracyjnego z podanymi wartosciami parametrow (tempo itd.)
        
    wyjscie:
        dict: parametry - zapisane nazwy i wartosci uzywanych parametrow
    
    """
    import re
    
    # wczytuje zawartosc pliku (bez pierwszej i ostatniej linijki, jeden wiersz wyjsciowej macierzy, zawiera
    # nazwe parametru i jego wartosc, jako oddzielne elementy, zapisane jako stringi)
    ustawienia = np.genfromtxt(plik_konfiguracyjny, dtype = str, skip_header=1, skip_footer=1, delimiter=":")
    
    # tworze slownik, ktory bedzie przechowywal wartosci
    parametry = {}
    
    # pozbywam się "" z key i przerabiam value na inty
    
    # jesli mamy 1 parametr, to ustawienia to zmienna o shape = (2,), wiec odwoluje sie bezposrednio do 
    # zmiennej ustawienia
    if ustawienia.shape == (2,): 
        parametry[re.sub('"','',ustawienia[0])] = int(ustawienia[1])
    else: # jak mamy wiecej parametrow odwoluje sie do kolejnych linijek macierzy ustawienia
        for l in ustawienia:  
            parametry[re.sub('"','',l[0])] = int(l[1])
    
    # zwracam gotowy slownik
    return parametry

b = wczytywanie_ustawien("defs.txt")

In [88]:
def tworzenie_piosenki(macierz_piosenki, czy_pelna = True, bpmy = 120):
    """
    glowna funkcja generujaca cala piosenke
    
    arg:
        numpy.ndarray (str: U2): macierz_piosenki - macierz zawierajaca definicje kolejnych cwiercnut 
                                (co ma byc grane w danej cwiercnucie)
        bool: czy_pelna - zmienna sprawdzajaca czy macierz_piosenki jest zapisana (nie jest, gdy tracki mialy
                          nieodpowiednia liczbe wierszy lub kolumn)
        int: bpmy - tempo piosenki w jednostce bpm
    """
    
    # macierz piosenki byla pusta, piosenka nie zostala utworzona
    if(czy_pelna == False):
        print("Nie utworzono piosenki")
        return None 
    
    else:
    
        import numpy as np
        import scipy.io.wavfile
        
        t_cwiercnuty = 60 / bpmy # czas trwania jednej cwiercnuty (zalezy od tempa)
        ile_cwiercnut = macierz_piosenki.shape[0] # ilosc cwiercnut
        kanaly = macierz_piosenki.shape[1] # ilosc uzywanych sampli
        frekw = 44100 # MOZE JAKO PARAMETR!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        czas_utworu = ile_cwiercnut*t_cwiercnuty
        ilosc_probek = int(frekw*czas_utworu) # ile elementow bedzie w nowym utworze
        
        # bedziemy tylko raz wczytywac zawartosc sampleXY.wav, wiec potrzebuje unikalne numery sampli
        rozne_sample = np.unique(macierz_piosenki) # bierze lacznie z "--"
        
        # w slownikach zapiszemy parametry tych sampli
        sample_co = {} # slownik z wartosciami danego sampla (tj. macierze numpy-owe z amplitudami)
        sample_frekw = {} # slownik z ich frekwencjami
        sample_dl = {} # slownik z ich dlugosciami
        
        #wczytujemy te sample
        for ktory_sampel in rozne_sample: # w iteratorze bierzemy napisy "01" "02"  "--" itd. stringi!!!
        
            if(ktory_sampel != '--'):
                # tworzymy napis z nazwa pliku sampla, np. "sample01.wav"
                plik = ''.join(['sample',ktory_sampel,'.wav'])
                # wczytujemy zawartosc i frekwencje danego sampla do odpowiednio nazwanego elementu 
                # w slowniku sample_co i sample_frekw
                sample_frekw[ktory_sampel], sample_co[ktory_sampel] = scipy.io.wavfile.read(plik)
                # tworzymy mono z naszego sampla
                sample_co[ktory_sampel] = np.mean(sample_co[ktory_sampel], axis=1)/32767
                # normalizujemy te wartosci
                sample_co[ktory_sampel] = np.int16(sample_co[ktory_sampel]/max(np.abs(sample_co[ktory_sampel]))\
                                                   *32767)
                # zapisujemy dlugosc sampli, czyli ilosc probek ( = czas_trwania*frekwencja)
                sample_dl[ktory_sampel] = sample_co[ktory_sampel].shape[0]
                
            else: # to samo robimy dla "--" recznie ustawiamy
                sample_co[ktory_sampel] = np.zeros((1,), dtype=np.int16) # robimy cisze, gdy --
                sample_frekw[ktory_sampel] = frekw # taka sama jak domyslna
                sample_dl[ktory_sampel] = 0 # zakladamy czas 0 sekund
         

        
        
        
        # definicja nowego utworu
        T = np.linspace(0, czas_utworu, ilosc_probek)
        
        for wiersz in range(0, ile_cwiercnut): # ZMIEN TU NA ile_cwiercnut ZAMIAST 10!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

            sample = [] # wczytamy sample z danej cwiecnuty
            dlugosci = [] # tu zapiszemy ich dlugosci w tej cwiercnucie

            for i in range(0, kanaly):
                
                sampus = macierz_piosenki[wiersz,i]
                sample.append(sample_co[sampus])   
                dlugosci.append(sample_dl[sampus])

                    
            # bierzemy najdluzszy sample i w calosci bedziemy go odtwarzac; reszte zatem tez w calosci
            # odtworzymy, a gdy sie skoncza damy cisze (zera)
            maksik = max(dlugosci)
            # mamy tutaj macierz 4 na max dlugosc, przygotowana do zlaczenia potem tych dzwiekow w jeden 
            pusty = np.int16(np.zeros((len(sample), maksik)))

            # dodajemy nasze dzwieki do tej pustej
            for k in range(0, len(sample)):
                pusty[k][0:dlugosci[k]] = sample[k]

            cwiercnuta = 0.2*pusty[0] + 0.4*pusty[1] + 0.3*pusty[2] + 0.1*pusty[3]#sum(pusty)
            
            # jesli dodanie ostatnich cwiercnut bedzie wiazalo sie z przekroczeniem dlugosci tworzonego
            # utworu, obcinamy ostatnie dzwieki, tak by zmiescic sie w tej dlugosci
            
            # poczatek biezacej cwiercnuty 
            poczatek_cwiercnuty = int(wiersz*t_cwiercnuty*frekw)
            
            # jesli dodanie ostatnich cwiercnut bedzie wiazalo sie z przekroczeniem dlugosci tworzonego
            # utworu, obcinamy ostatnie dzwieki, tak by zmiescic sie w tej dlugosci
            if (poczatek_cwiercnuty + maksik) > ilosc_probek:
                
                T[poczatek_cwiercnuty:(poczatek_cwiercnuty + maksik)]=\
                cwiercnuta[0:len(T[poczatek_cwiercnuty:(poczatek_cwiercnuty + maksik)])]
                
            else:
                T[poczatek_cwiercnuty:(poczatek_cwiercnuty + maksik)] += cwiercnuta
        
        T= np.array(T, dtype=np.int16)
        

        return T

pios, k = wczytywanie_sciezek(a)
wierszyk = tworzenie_piosenki(pios, k, b['bpm'])

wierszyk

/home/rexamine/anaconda/lib/python3.4/site-packages/scipy/io/wavfile.py:172: WavFileWarning: Chunk (non-data) not understood, skipping it.
  WavFileWarning)


array([   16,   -40,    32, ..., -4209, -4304, -4325], dtype=int16)

array([ 0,  0,  0, ..., 22, 22, 23], dtype=int16)

In [62]:
h[0:1]

array([ 0.])

In [49]:
h = np.linspace(0,1,5.9) 


In [91]:
import numpy as np
import scipy.io.wavfile
import scipy.signal

# dac ifa ze jak wierszyk = none to nic nie robić

scipy.io.wavfile.write('test1.wav', 
                           44100,
                       wierszyk
                        )


In [92]:
!!aplay /home/rexamine/Desktop/test1.wav

["Playing WAVE '/home/rexamine/Desktop/test1.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Mono"]